services:
  - type: web
    name: fastapi-ecommerce-api
    env: python
    plan: free # or starter, standard, pro
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_NAME
        value: ecommerce
      # MONGODB_URI will be added via dashboard
